apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    "strimzi.io/cluster": cluster-development
  name: "dev.receiver.json"
  namespace: streaming
spec:
  config:
    retention.ms: 5257000000
    segment.bytes: 1073741824
  partitions: 12
  replicas: 1
