apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: remove-node
  labels:
    strimzi.io/cluster: cluster-development
#  annotations:
#    strimzi.io/rebalance-auto-approval: "true"
  namespace: streaming
spec:
  mode: remove-brokers
  brokers:
    - 1
  skipHardGoalCheck: true
