---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin
  namespace: streaming
  labels:
    strimzi.io/cluster: cluster-development
spec:
  # create authentication means for this user : mtls, password, sasl
  authentication:
    type: "tls"
  authorization:
    type: simple
    acls:
      - host: "*"
        operations:
          - "All"
        resource:
          name: "*"
          type: "topic"
          patternType: "literal"
      - host: "*"
        operations:
          - "All"
        resource:
          type: "cluster"
      - host: "*"
        operations:
          - "All"
        resource:
          name: "*"
          type: "group"
          patternType: "literal"
      - host: "*"
        operations:
          - "All"
        resource:
          name: "*"
          type: "transactionalId"
          patternType: "literal"
